### ISSUE TITLE
Why nothing about Riseup ?

### ISSUE THREAD

**Issue by smonff** [OpenTechFund/secure-email#39]
Riseup is not new nor decentralized, but it got interesting positions about privacy. Why not including it in the list?

**Comment by elijh** [comment]
hehe, well, i started riseup but we don't offer client-side encryption, unless you install mailvelope. riseup is in the process of deploying LEAP as an optional choice for users who want higher security.

**Comment by smonff** [comment]
Oh! Interesting.
